# Generated by Django 3.2.7 on 2021-10-20 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_expense_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
    ]
