# Generated by Django 3.2.7 on 2021-11-07 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_auto_20211107_0047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
