# Generated by Django 3.2.7 on 2021-11-09 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_auto_20211109_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.RemoveField(
            model_name='income',
            name='category',
        ),
    ]
