# Generated by Django 3.2.7 on 2021-11-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_auto_20211109_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Necessities', 'Necessities'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], default='Food', max_length=20),
        ),
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Necessities', 'Necessities'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], default='Food', max_length=20),
        ),
    ]
