# Generated by Django 3.2.7 on 2021-12-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0013_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('Paycheck', 'Paycheck'), ('Side Hustle', 'Side Hustle'), ('Gift', 'Gift')], default='Paycheck', max_length=20),
        ),
    ]
